jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            CARDS:
                namespace_prefix: 'App\Entity\Card'
                path: '%kernel.root_dir%/Resources/config/serializer/CARDS'
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
