version: '2.2'
services:
  nginx:
    container_name: a51-kanban_nginx
    image: nginx:1.13.8
    ports:
      - "80:80"
    volumes:
      - ./:/app/
      - ./logs/nginx/:/var/log/nginx
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php7

  php7:
    container_name: a51-kanban_php7
    build: ./docker/php
    links:
      - devdb

    working_dir: /app
    volumes:
      - ./:/app/
      - ./frontend:/app/frontend
      - ./docker/php/zshrc.tpl:/root/.zshrc
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/conf.d/custom-xdebug-local.ini:/usr/local/etc/php/conf.d/custom-xdebug-local.ini
    ports:
      - 8111:8111
      - 8222:8222
      - 5555:5555
  devdb:
    container_name: a51-kanban_devdb
    image: mysql:5.6
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: a51-kanban
      MYSQL_DATABASE: a51-kanban
      MYSQL_USER: a51-kanban
      MYSQL_PASSWORD: a51-kanban

  nodejs:
    entrypoint: tail -F -n0 /etc/hosts
    container_name: a51-kanban_nodejs
    build: ./docker/nodejs
    working_dir: /app/frontend
    volumes:
      - ./:/app
    ports:
      - 3000:3000
volumes:
  esdata1:
    driver: local
