nelmio_api_doc:
    documentation:
#        host: "%base_url%"
        schemes: [http, https]
        info:
            title: A51 Kanban
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
#            - ^/api(?!/doc/$) # Accepts routes under /api except /api/doc
#        host_patterns:
#            - ^api\.